config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index, :show]
  resources :user_goals, only: [:index]

  resources :goals, only: [:show, :create, :new] do
    member do
      get :random_motivation
      put :disable
    end
  end

  put 'user_goals/:id/share' => 'user_goals#share', as: :share_goal
  put 'goals_in_list/:id/add_to_list' => 'goals_in_list#add_goal_to_list', as: :add_to_goal_list
  put 'goals_in_list/:id/done' => 'goals_in_list#done', as: :done_goal
  put 'goals_in_list/:id/fail' => 'goals_in_list#fail', as: :fail_goal

  get 'about' => "main#about"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :goals
  has_many :available_goals, -> { available_for_all }, class_name: "Goal"

  validates :name, presence: true

  scope :weighted, -> { order('weight asc') }

  delegate :count, to: :goals, prefix: true

  def self.shared
    find_by_name("Shared")
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  has_many :motivations
  has_many :goal_in_lists
  has_many :goal_lists, through: :goal_in_lists

  accepts_nested_attributes_for :motivations

  validates :title, :user, :category, :motivations, presence: true
  delegate :name, to: :user, prefix: true

  scope :available_for_all, -> { where(shared: true).where(approved: true) }

  after_create :add_to_user_goal_list

  delegate :name, to: :category, prefix: true
  delegate :name, to: :user, prefix: true


  def motivations_attributes=(attrs)
    source_or_title = attrs.find_all{|k,v| (v[:source] + v[:title]).present?}
    not_empty_attrs = Hash[source_or_title]
    super(not_empty_attrs)
  end

  def share!
    update_attribute(:shared, true)
  end

  def disapprove!
    update_attribute(:approved, false)
  end


  protected


  def add_to_user_goal_list
    user.goal_list.add_goal(self) unless user.admin?
  end
end

app/models/goal_in_list.rb
class GoalInList < ActiveRecord::Base
  include AASM

  belongs_to :goal
  belongs_to :goal_list

  delegate :title, to: :goal

  aasm do
    state :pending, initial: true
    state :done
    state :failed

    event :achieve_dream do
      transitions from: :pending, to: :done
    end

    event :fail_dream do
      transitions from: :pending, to: :failed
    end
  end

  scope :pending, -> {where(aasm_state: 'pending')}
  scope :done, -> {where(aasm_state: 'done')}
  scope :failed, -> {where(aasm_state: 'failed')}

end

app/models/goal_list.rb
class GoalList < ActiveRecord::Base
  belongs_to :user
  has_many :goal_in_lists
  has_many :goals, through: :goal_in_lists

  validates :user, presence: true

  def add_goal(goal)
    exist_pending_goal = goal_in_lists
      .where(goal_id: goal.id, aasm_state: :pending).first
    goal_shared_and_approved = goal.shared? && goal.approved?
    goal_owner = (goal.user == user)

    if (goal_owner || goal_shared_and_approved) && !exist_pending_goal
      goal_in_list = goal_in_lists.build
      goal_in_list.goal = goal
      fail("Goal not saved in add_goal!") unless goal_in_list.save
      return true
    else
      return false
    end
  end

  def is_pending?(goal)
    goal_in_list = goal_in_lists.where(goal_id: goal.id, aasm_state: 'pending')
      .first
    goal_in_list
  end
end

app/models/motivation.rb
class Motivation < ActiveRecord::Base
  belongs_to :goal

  validates :title, :source, presence: true

  def source_is_url?
    source['http://'].present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable,
         :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:github, :twitter]

  has_many :goals    # Goals which created by user
  has_one :goal_list # Goals to be done

  delegate :goal_in_lists, to: :goal_list

  def goal_list
    super || (build_goal_list.save! && goal_list)
  end

  def grouped_goals_in_list
    goal_in_lists.group_by{ |goal_in_list| goal_in_list.aasm_state }
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email || "email-#{SecureRandom.uuid}@example.com"
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @shared_category = Category.shared
    @categories = Category.weighted - [@shared_category]

    if params[:screenshot] == "true"
      filepath = "#{Rails.root}/public/screenshoot-planamp.png"
      render :text => File.open(filepath, 'rb').read,
             :status => 200, :content_type => 'image/png'
    end
  end

  def show
    @category_with_goals = Category.find(params[:id])
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @category_with_goals = Category.weighted.includes(:available_goals)
  end

  def new
    @goal = Goal.new
    #TODO: It should be dynamic
    motivations_count = 3
    motivations_count.times{ @goal.motivations.build }
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    if current_user.admin?
      @goal.shared = true #NOTE: This line only for admin
    else
      @goal.category = Category.shared
    end

    if @goal.save
      redirect_to @goal, success: "Goal successfully created!"
    else
      render 'new'
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def random_motivation
    @goal = Goal.find(params[:id])
    render json: @goal.motivations.sample
  end

  def disable
    @goal = Goal.find(params[:id])
    @goal.disapprove!
    redirect_to :back, notice: 'Tried to disapprove'
  end


  protected


  def goal_params
    params.require(:goal).permit(:title, :description, :category_id, :shared,
      motivations_attributes: [:id, :title, :source, :description])
  end
end

app/controllers/goals_in_list_controller.rb
class GoalsInListController < ApplicationController
  before_action :authenticate_user!

  def done
    goal_in_list = GoalInList.find(params[:id])
    goal_in_list.achieve_dream!

    redirect_to :back
  end

  def fail
    goal_in_list = GoalInList.find(params[:id])
    goal_in_list.fail_dream!

    redirect_to :back
  end

  def add_goal_to_list
    @goal = Goal.find(params[:id])
    goal_list = current_user.goal_list
    if goal_list.add_goal(@goal)
      flash[:notice] = "Goal successfully added to your goal list"
      redirect_to user_goals_url
    else
      flash[:error] = "Error on adding goal to goal list"
      redirect_to :back
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def about
  end

end

app/controllers/user_goals_controller.rb
class UserGoalsController < ApplicationController
  before_action :authenticate_user!

  def index
    @goals = current_user.goals
    @goals_in_list = current_user.grouped_goals_in_list
    @empty_goals_in_list = current_user.goal_in_lists.blank?
  end

  # Move to another controller
  def share
    @goal = Goal.find(params[:id])
    if @goal.share!
      flash[:notice] =  "Goal successfully shared!
        Now everyone can access it through <Shared> category."
    else
      flash[:error] = "Error in goal sharing"
    end

    redirect_to(action: :index)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    oauth_sign_in(:github)
  end

  def twitter
    oauth_sign_in(:twitter)
  end


  protected


  def oauth_sign_in(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: provider)
      end
      sign_in_and_redirect(@user, event: :authentication) and return
    else
      flash[:error] = "Error in auth"
      redirect_to(root_url) and return
    end
  end

  def after_omniauth_failure_path_for(scope)
    root_path
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title( page_title )
    content_for(:title) { page_title }
  end

  def body_class( klass )
    content_for(:body_class) { klass}
  end
end

app/views/categories/index.html.haml
%div.b-categories
  %h2.b-categories__title Go into the section you are interested in and choice the <b>goal</b>
  - @categories.each do |category|
    =link_to "#{category.name} <span>#{category.goals_count}</span>".html_safe, category, class: 'b-categories__item b-categories__item_' + category.name.downcase
  = link_to "#{@shared_category.name} <span>#{@shared_category.goals_count}</span>".html_safe, @shared_category, class: 'b-categories__item b-categories__item_shared'

app/views/categories/show.html.haml
= body_class(@category_with_goals.name.downcase)
%div.b-categories
  %h2.b-categories__title #{@category_with_goals.name} #{link_to "All categories", categories_path, class: 'b-categories__title-link'}
  - if @category_with_goals == Category.shared
    %div{style: "text-align: right; padding-bottom: 25px; margin-top: -15px;"}
      = link_to "Make your goal and share it!", new_goal_path

  %div.b-categories__goals
    - @category_with_goals.available_goals.each do |goal|
      %a.b-categories__goals-item{href: "#{goal_path(goal)}"}
        %span.b-categories__goals-item-title= goal.title
        %span.b-categories__goals-item-desc= goal.description

app/views/goals/_form.html.haml
= simple_form_for @goal do |f|
  - if current_user.admin?
    = f.association :category, include_blank: false
  = f.input :title, input_html: { size: 50 }
  = f.input :description, input_html: { rows: 7, cols: 37 }

  -# At least one motivation needed

  = f.simple_fields_for :motivations, @goal.motivations.build do |m|
    = m.input :title, required: true, label: 'Motivation title', input_html: { size: 50 }
    = m.input :description, required: true, label: 'Motivation description', |
    input_html: { rows: 7, cols: 37 }
    = m.input :source, required: true, label: 'Motivation source', input_html: { size: 50 }

  = link_to "Add more motivations", '#', id: 'show-other-motivations'
  #other-motivations{style: 'display: none;'}
    = f.simple_fields_for :motivations do |m|
      = m.input :title, required: false, label: 'Motivation title', input_html: { size: 50 }
      = m.input :description, required: false, label: 'Motivation description', |
      input_html: { rows: 7, cols: 37 }
      = m.input :source, required: false, label: 'Motivation source', input_html: { size: 50 }
      %p ----------------------------------------------------
  = f.input :shared, label: 'Check to share in <Shared> category'
  = f.button :submit

:javascript
  $(function() {
    $('#show-other-motivations').click(function () {
      $("#other-motivations").toggle();
      $('#show-other-motivations').toggle();
    })
  })

app/views/goals/_motivation.html.haml
.b-categories__motivations-item
  %div.b-categories__motivations-item-title= motivation.title
  %div.b-categories__motivations-item-description= motivation.description
  %div.b-categories__motivations-item-source
    <b>Source:</b>
    - if motivation.source_is_url?
      #{link_to motivation.source, motivation.source}
    - else
      #{link_to motivation.source, '#'}

app/views/goals/index.html.haml
-#%h1 GoalsController#index
-#
-#- @category_with_goals.each do |category|
-#  %h2 <b>Category:</b> #{category.name}
-#  - category.available_goals.each do |goal|
-#    %p
-#      %b Title
-#      #{link_to goal.title, goal}
-#    %p
-#      %b Created by
-#      #{goal.user_name}
-#  %p ------------------------------------------
-#

app/views/goals/new.html.haml
%h2 Create Your Own Goal
%div.b-form
  = render partial: 'form'

app/views/goals/show.html.haml
= page_title("Planamp - #{@goal.title}")

%h2.b-categories__title #{@goal.title} #{link_to @goal.category_name, @goal.category, class: 'b-categories__title-link'}

%p.goal-description= @goal.description

- if current_user && current_user.admin?
  = link_to "Disable goal", disable_goal_path(@goal), method: :put

%div.b-categories__creator Created by #{link_to @goal.user_name, '#'}
= link_to 'Motivate Me!', '#', class: 'b-categories__motivations-link'
.b-categories__motivations{style: 'display:none'}
  = render partial: 'motivation', collection: @goal.motivations


%div.b-categories__social
  = render partial: 'shared/share_buttons'
%div.b-categories__add-own-list
  - if current_user && current_user.goal_list.is_pending?(@goal)
    Goal already in #{link_to "your goal list", user_goals_url}
  - else
    = link_to 'Add to own list', add_to_goal_list_path(@goal), method: :put


= render partial: 'shared/disqus'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? content_for(:title) : "Planamp - Motivations for Your Goals"
    = stylesheet_link_tag '/css/styles', media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:300,400,700&subset=latin,cyrillic-ext", :rel => "stylesheet", :type => "text/css"}/
    :javascript
      var switchTo5x=true;
    %script{:src => "http://w.sharethis.com/button/buttons.js", :type => "text/javascript"}
    :javascript
      stLight.options({publisher: "d9e3b58a-eb41-43f1-b570-aef8ebe91ac5", doNotHash: false, doNotCopy: false, hashAddressBar: true});

  %body{class: "#{content_for?(:body_class) ? content_for(:body_class) : ''}"}
    %div.b-header
      %div.b-wrapper.clearfix
        %div.b-header__name= link_to "Planamp", root_path, class: 'b-header__name-link';
        %div.b-header__menu= render partial: 'shared/menu'
    %div.b-content
      %div.b-wrapper.clearfix
        = render partial: 'shared/messages'
        = yield

    %div.b-footer
      %div.b-wrapper.clearfix
        = link_to "About", about_path, class: 'b-footer__left'
        %span{class: 'b-footer__right'} © 2014 RailsRumble
        = render partial: 'shared/yandex_metrika'
        = render partial: 'shared/swell'
        = render partial: 'shared/rails_rumble'

app/views/main/about.html.haml
%h1 Welcome!

%p We are developing goal motivation app which helps you to achieve your goals.
%p
  Almost everyone try to write goals into paper and then forget about it, because
  paper is not motivating us.
%p
  Our app provides goals with motivations. You can choice a goal and see what can motivate you to
  achieve it.
%p Also app provides functionality to add goal into list and track it.
%p The last functionality is social. User can create own goal with motivations. Than user can
share this goal for the whole app. This goal will be in #{link_to "Shared category", Category.shared}.

%br
%br

%p
  Thank you for support. Feel free to contact us!

%p <a href="http://lnkd.in/WuyUTN"> Idris Yusupov </a>, <a href="mailto:wibox@ya.ru">Andrey Arkhipov</a>

app/views/main/index.html.haml
%h1.landing Planamp
%p.landing Motivations for Your Goals
%p{style: 'text-align: center'} Coming soon


%div.b-header__name= link_to "Planamp", categories_path, class: 'b-header__name-link';

app/views/shared/_disqus.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'planamp'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.

app/views/shared/_menu.html.haml
= link_to "Your goals", user_goals_path, class: 'b-header__menu-item b-header__menu-item_yourgoals'
= link_to "Make goal", new_goal_path, class: 'b-header__menu-item b-header__menu-item_makegoal'

- if current_user
  = link_to "Sign out", destroy_user_session_path, method: :delete, class: 'b-header__menu-item b-header__menu-item_signout'
- else
  -# link_to "Sign in", new_user_session_path, class: 'b-header__menu-item b-header__menu-item_signin'
  %span.b-header__menu-item_signin Sign in with
  = link_to "", user_omniauth_authorize_path(:github, origin: request.original_url), class: 'b-header__menu-item_github'
  = link_to "", user_omniauth_authorize_path(:twitter, origin: request.original_url), class: 'b-header__menu-item_twitter'

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "flash-message #{name}"}
      %p #{msg}

app/views/shared/_rails_rumble.html.haml
:javascript
  var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
  rumbleBannerBackgroundColor = "#161616";
  rumbleBannerTextColor = "#b0b0b0";
  rumbleBannerLinkColor = "#ffffff";
  rumbleBannerPlacement = "bottom"; // Optionally replace with "bottom".
%script{:src => "https://d4nnn7wspfa3h.cloudfront.net/banner-2014.js", :type => "text/javascript"}

app/views/shared/_share_buttons.html.haml
%span.st_twitter_large{:displaytext => "Tweet"}
%span.st_facebook_large{:displaytext => "Facebook"}
%span.st_evernote_large{:displaytext => "Evernote"}
%span.st_vkontakte_large{:displaytext => "Vkontakte"}

app/views/shared/_swell.html.haml
/ Place this code before your site's </body> tag.
%script{:charset => "utf-8", :type => "text/javascript"}
  :cdata
    var _swell_site_ids = _swell_site_ids || [];
    _swell_site_ids.push('1e52e861');
    (function() {
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = '//df50assd5876f.cloudfront.net/assets/hello-3b9181727ebdc6002c5bb5da48a2257f.js';
    ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
    })();
%noscript
  %img{:src => "//heyswell.com/v1/hello.gif?sites=1e52e861&javascript=0"}/

app/views/shared/_yandex_metrika.html.haml
/ Yandex.Metrika counter
:javascript
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter26685681 = new Ya.Metrika({id:26685681,
                      webvisor:true,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true});
          } catch(e) { }
      });
  
      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
  
      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
%noscript
  %div
    %img{:alt => "", :src => "//mc.yandex.ru/watch/26685681", :style => "position:absolute; left:-9999px;"}/
/ /Yandex.Metrika counter

app/views/user_goals/index.html.haml
%div.b-categories
  %h2.b-categories__title Your goal list
  - if @empty_goals_in_list
    = link_to "View goals", categories_path

  - if @goals_in_list['pending']
    %div.b-categories__goals-counter.b-categories__goals-counter_first Pending count: <span class="b-categories__goals-counter-pen">#{@goals_in_list['pending'].count}</span>

  - if @goals_in_list['pending']
    .b-categories__goals
      - @goals_in_list['pending'].each do |goal_in_list|
        %div.b-categories__goals-item.b-categories__goals-item_your
          = link_to goal_in_list.title, goal_in_list.goal, class: 'b-categories__goals-item-title'
          = link_to "Motivate me!", '#', class: 'b-categories__goals-item-btn b-categories__goals-item-btn_info', |
          data: {id: goal_in_list.goal.id};
          = link_to "Fail", fail_goal_path(goal_in_list), method: :put, class: 'b-categories__goals-item-btn b-categories__goals-item-btn_fail';
          = link_to "Done", done_goal_path(goal_in_list), method: :put, class: 'b-categories__goals-item-btn b-categories__goals-item-btn_done';

  - if @goals_in_list['done']
    %div.b-categories__goals-counter Done count: <span class="b-categories__goals-counter-done">#{@goals_in_list['done'].count}</span>
    .b-categories__goals.b-categories__goals-done
      - @goals_in_list['done'].each do |goal_in_list|
        %div.b-categories__goals-item.b-categories__goals-item_your
          = link_to goal_in_list.title, goal_in_list.goal, class: 'b-categories__goals-item-title'

  - if @goals_in_list['failed']
    %div.b-categories__goals-counter Failed count: <span class="b-categories__goals-counter-fail">#{@goals_in_list['failed'].count}</span>
    .b-categories__goals.b-categories__goals-fail
      - @goals_in_list['failed'].each do |goal_in_list|
        %div.b-categories__goals-item.b-categories__goals-item_your
          = link_to goal_in_list.title, goal_in_list.goal, class: 'b-categories__goals-item-title'

  %h2.b-categories__title Created by you
  %div.b-categories__goals-counter.b-categories__goals-counter_first Total count:  <span class="b-categories__goals-counter-pen">#{@goals.count}</span>
  - if @goals.empty?
    = link_to "Make your own goal", new_goal_path, style: 'padding-bottom: 20px; display: inline-block'
  %div.b-categories__goals
    - @goals.each do |goal|
      %div.b-categories__goals-item
        = link_to goal.title, goal, class: 'b-categories__goals-item-title'
        - if goal.shared?
          %div.b-categories__goals-item-desc Shared for everyone!
        - else
          = link_to 'Share for everyone!', share_goal_path(goal), method: :put, confirm: true

  .popup-motivation{style: 'display:none'}
    %a{class: "b-close"}X

:javascript
  $(function() {
    $('.b-categories__goals-item-btn.b-categories__goals-item-btn_info').click(function () {
      var goalId = $(this).data()['id'];
      var url = '/goals/' + goalId + '/random_motivation'
      $.ajax({
        dataType: "json",
        url: url,
        async: false,
        success: function(result){
          var motivationHtml = "<a class='b-close'>x<a/>";
          motivationHtml += "<strong>" + result.title + "</strong>";
          motivationHtml += "<p>" + result.description + "</p>";
          motivationHtml += "<strong>Source: </strong>" + result.source;
          $('.popup-motivation').html(motivationHtml);
          $('.popup-motivation').bPopup();
       }
      });
    })
  })